// packages/react/src/index.ts
import {runSpeedtest, type SpeedtestClientOptions, SpeedtestTimeoutError} from '@staffetta/client'
import type {SpeedtestLogEntry, SpeedtestStatus} from '@staffetta/core'
import {useCallback, useEffect, useRef, useState} from 'react'

export type {
  SpeedtestLogEntry,
  SpeedtestPhase,
  SpeedtestResult,
  SpeedtestStatus,
  SpeedtestVerdict,
} from '@staffetta/core'

export type UseSpeedtestOptions = Omit<SpeedtestClientOptions, 'signal' | 'onPhase' | 'onSample'>

/**
 * Drives one speedtest at a time: `start()` is a no-op while a test is running, `cancel()`
 * aborts it (also on unmount) returning to the idle state. `options` is read when `start()`
 * is called, so an inline object literal is fine.
 */
export function useSpeedtest(options: UseSpeedtestOptions): UseSpeedtestContract {
  const [status, setStatus] = useState<SpeedtestStatus>({kind: 'idle'})
  const [log, setLog] = useState<Array<SpeedtestLogEntry>>([])
  const optionsRef = useRef(options)
  optionsRef.current = options
  const abortControllerRef = useRef<undefined | AbortController>(undefined)

  // Aborts a test left running on unmount.
  useEffect(() => () => abortControllerRef.current?.abort(), [])

  const start = useCallback(() => {
    if (abortControllerRef.current && !abortControllerRef.current.signal.aborted) {
      return
    }

    const abortController = new AbortController()
    abortControllerRef.current = abortController
    setStatus({kind: 'running', phase: 'ping'})
    setLog([])

    runSpeedtest({
      ...optionsRef.current,
      signal: abortController.signal,
      onPhase: phase => {
        setStatus({kind: 'running', phase})
        setLog(prev => [...prev, {kind: 'phase', phase}])
      },
      onSample: sample => {
        setLog(prev => [...prev, {kind: 'sample', sample}])
      },
    }).then(
      result => {
        abortControllerRef.current = undefined
        setStatus({kind: 'done', result})
      },
      (error: unknown) => {
        abortControllerRef.current = undefined

        if (abortController.signal.aborted) {
          // Cancelled by the user (or unmount): back to the initial state, no leftover output.
          setStatus({kind: 'idle'})
          setLog([])
          return
        }

        if (error instanceof SpeedtestTimeoutError) {
          setStatus({kind: 'error', reason: 'timeout', error, partial: error.partial})
          return
        }

        const isTimeout = error instanceof DOMException && error.name === 'TimeoutError'
        setStatus({kind: 'error', reason: isTimeout ? 'timeout' : 'failed', error})
      },
    )
  }, [])

  const cancel = useCallback(() => {
    abortControllerRef.current?.abort()
  }, [])

  return {status, log, start, cancel}
}

// Types ///////////////////////////////////////////////////////////////////////

export interface UseSpeedtestContract {
  status: SpeedtestStatus
  log: Array<SpeedtestLogEntry>
  start: () => void
  cancel: () => void
}

// packages/angular/src/index.ts
import {type Provider, type Signal, signal} from '@angular/core'
import {runSpeedtest, type SpeedtestClientOptions, SpeedtestTimeoutError} from '@staffetta/client'
import type {SpeedtestLogEntry, SpeedtestStatus} from '@staffetta/core'

export type {
  SpeedtestLogEntry,
  SpeedtestPhase,
  SpeedtestResult,
  SpeedtestStatus,
  SpeedtestVerdict,
} from '@staffetta/core'

export type SpeedtestServiceOptions = Omit<SpeedtestClientOptions, 'signal' | 'onPhase' | 'onSample'>

/**
 * Drives one speedtest at a time: `start()` is a no-op while a test is running, `cancel()`
 * aborts it returning to the idle state. Deliberately decorator-free (plain class + signals),
 * so it ships as regular ESM without an Angular compiler in the loop — register it with
 * {@link provideSpeedtest} (Angular then calls `ngOnDestroy`, aborting a test left running
 * when the owning injector is destroyed) or instantiate it directly.
 */
export class SpeedtestService {
  private readonly statusSignal = signal<SpeedtestStatus>({kind: 'idle'})
  private readonly logSignal = signal<Array<SpeedtestLogEntry>>([])
  private abortController: undefined | AbortController = undefined

  readonly status: Signal<SpeedtestStatus> = this.statusSignal.asReadonly()
  readonly log: Signal<Array<SpeedtestLogEntry>> = this.logSignal.asReadonly()

  start(options: SpeedtestServiceOptions): void {
    if (this.abortController && !this.abortController.signal.aborted) {
      return
    }

    const controller = new AbortController()
    this.abortController = controller
    this.statusSignal.set({kind: 'running', phase: 'ping'})
    this.logSignal.set([])

    runSpeedtest({
      ...options,
      signal: controller.signal,
      onPhase: phase => {
        this.statusSignal.set({kind: 'running', phase})
        this.logSignal.update(prev => [...prev, {kind: 'phase', phase}])
      },
      onSample: sample => {
        this.logSignal.update(prev => [...prev, {kind: 'sample', sample}])
      },
    }).then(
      result => {
        this.abortController = undefined
        this.statusSignal.set({kind: 'done', result})
      },
      (error: unknown) => {
        this.abortController = undefined

        if (controller.signal.aborted) {
          // Cancelled by the user (or injector destroy): back to the initial state, no leftover output.
          this.statusSignal.set({kind: 'idle'})
          this.logSignal.set([])
          return
        }

        if (error instanceof SpeedtestTimeoutError) {
          this.statusSignal.set({kind: 'error', reason: 'timeout', error, partial: error.partial})
          return
        }

        const isTimeout = error instanceof DOMException && error.name === 'TimeoutError'
        this.statusSignal.set({kind: 'error', reason: isTimeout ? 'timeout' : 'failed', error})
      },
    )
  }

  cancel(): void {
    this.abortController?.abort()
  }

  ngOnDestroy(): void {
    this.cancel()
  }
}

/**
 * Registers {@link SpeedtestService} in an injector without decorator metadata — add it to a
 * component's `providers` (one test per component, cleaned up with it) or to the bootstrap
 * providers for an app-wide instance. Then `inject(SpeedtestService)` as usual.
 */
export function provideSpeedtest(): Provider {
  return {provide: SpeedtestService, useFactory: () => new SpeedtestService()}
}
